name: landmapper-test

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - dask 
  - earthengine-api
  - folium
  - geopandas
  - jupyter
  - matplotlib
  - numpy>=1.18,<1.22
  - pandas
  - python=3.9
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pydantic=1.9.2
  - rasterio
  - rasterstats
  - richdem
  - rio-cogeo
  - scikit-image<=0.18.2
  - scikit-learn>=1.0
  - scipy
  - seaborn
  - shapely
  - sphinx
  - torchvision=0.15.2
  - torchmetrics 
  - tqdm
  - pysheds
  - pip
  - pip:
      - geetools=0.6.14
      - python-dotenv>=0.5.1
      - torchgeo
      - wget
      - git+https://github.com/Ecotrust/gdstools@v0.1
      - -e .
