name: landmapper-env

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - dask 
  - earthengine-api
  - folium
  - geopandas
  - graphviz
  - imbalanced-learn
  - jupyter
  - matplotlib
  - pandas
  - pdal
  - pystac=1.8
  - pyproj
  - pysheds
  - python=3.10
  - python-pdal
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pydantic=1.9.2
  - rasterio
  - rasterstats
  - richdem
  - rio-cogeo
  - scikit-image
  - scikit-learn
  - scikit-optimize
  - scipy
  - seaborn
  - shapely
  - sphinx
  - torchvision=0.15.2
  - torchmetrics 
  - tqdm
  - pip
  - pip:
      - autorank 
      - geetools
      - python-dotenv>=0.5.1
      - torchgeo
      - -e . # install the package in editable mode
